# Generated by Django 4.2.3 on 2023-07-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userprofile_fb_url_userprofile_insta_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='insta_url',
            new_name='instagram_url',
        ),
    ]
