# Generated by Django 4.2.3 on 2023-07-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_profile_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_pic',
        ),
    ]
