# Generated by Django 4.2.3 on 2023-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_profile_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/category'),
        ),
    ]
